trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validate
  jobs:
    - template: pipelines/templates/terraform-validate.yml

- stage: Plan
  dependsOn: Validate
  jobs:
    - template: pipelines/templates/terraform-plan.yml

- stage: Apply
  dependsOn: Plan
  condition: succeeded()
  jobs:
    - template: pipelines/templates/terraform-apply.yml