jobs:
- job: TerraformValidate

  displayName: Validate Terraform

  steps:

  - checkout: self

  - task: TerraformInstaller@1
    displayName: Install Terraform

    inputs:
      terraformVersion: '1.5.7'

  - task: AzureCLI@2
    displayName: Terraform Validate

    inputs:
      azureSubscription: 'Azure-git-terraform-pipeline'
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true

      inlineScript: |

        echo "Changing directory..."

        cd $(System.DefaultWorkingDirectory)/environments/dev

        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_TENANT_ID=$tenantId

        echo "Running terraform init..."

        terraform init

        echo "Checking terraform formatting..."

        terraform fmt -check

        echo "Running terraform validate..."

        terraform validate